### ISSUE TITLE
Remove/replace README.md

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli-bundle#16]
It seems `README.md` is a copy of `wp-cli/wp-cli`. It'll be problematic to have duplicated documentation. What should this `README.md` contain?

**Comment by schlessera** [comment]
I think the `README.md` of the `wp-cli/wp-cli-bundle` repo should contain information directly pertaining to the "bundle":
- What does the the "bundle" represent?
- How are commands determined to be part of the "bundle"
- How is the release system tied to this repo?
- What is the special versioning behavior of the bundle (mirroring `wp-cli/wp-cli` package)?

Some or most of these can be summaries pointing to the handbook.
