### ISSUE TITLE
Missing 2.4.1 release

### ISSUE THREAD

**Issue by 0x6d617474** [wp-cli/wp-cli-bundle#183]
Although `wp-cli/wp-cli` has released `2.4.1`, there has been no tagged release of `wp-cli/wp-cli-bundle` with an updated lock file. Once wp-cli/wp-cli#5359 has been fixed to account for the outdated version reporting, the `composer.lock` file should be updated, and a new release tagged to match `wp-cli/wp-cli`.

**Comment by lkraav** [comment]
Yeah I've veen typing wp cli update to no avail for a while now.

**Comment by szepeviktor** [comment]
@schlessera What can I do to trigger the building of this release?

**Comment by schlessera** [comment]
Yes, indeed. There is no release, this was just a hotfix for a Composer issue.
