### ISSUE TITLE
composer global require wp-cli/wp-cli-bundle

### ISSUE THREAD

**Issue by michaelr0** [wp-cli/wp-cli-bundle#247]
Hi There,

When running composer version 2+ I'm finding that the use of composer global require wp-cli/wp-cli-bundle causes composer 1.10.17 to be installed in my global vendor/bin, which due to being in my $PATH is causing composer 1.10 to be used rather than 2+

Thanks.

**Comment by schlessera** [comment]
This should be solved with v2.5.0, which uses Composer v2 for the package manager as well.
