### ISSUE TITLE
Allow composer ^2.0

### ISSUE THREAD

**Issue by mremi** [wp-cli/wp-cli-bundle#348]
Hi,

Would it be possible to support composer ^2.0 instead of ^2.0.0? Thus allowing versions >=2.0 and <3.0.

Thanks

**Comment by schlessera** [comment]
Hi @mremi ,

The caret (`^`) constraint is already doing what you want. You seem to be confusing it with the tilde constraint (`~`). See https://getcomposer.org/doc/articles/versions.md#caret-version-range-
