### ISSUE TITLE
Support composer/composer 2.3+

### ISSUE THREAD

**Issue by oxyc** [wp-cli/wp-cli-bundle#558]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Currently this package locks itself to composer/composer 2.2 which only supports [symfony/console ^5.0](https://github.com/composer/composer/blob/30ff21a9af9a10845436abaeeb0bb7276e996d24/composer.json#L35). To support eg. [roots/acorn](https://github.com/roots/acorn/) v3 (illuminate v9) symfony/console ^6.0 is required but currently having wp-cli-bundle as a dependency prevents that.

Note that previous versions of WP-CLI did have this unlocked so I am able to update some packages however with older WP-CLI throws PHP 8.2 notices.

**Describe the solution you'd like**

Unlock composer/composer to at least v2.3 but ideally support up to latest version.

**Comment by danielbachhuber** [comment]
Thanks for the report, @oxyc 

There's some existing conversation on https://github.com/wp-cli/package-command/issues/172 if you'd like to help with the efforts there.
