### ISSUE TITLE
Release 2.9.1, to allow having composer 2.6 on board

### ISSUE THREAD

**Issue by gggeek** [wp-cli/wp-cli-bundle#606]
I just checked my install, and it seems that I still have composer 2.2.22 installed, despite being on version 2.9.0 of this package

```
web@website:/var/www/website (main)$ composer depends composer/composer
wp-cli/package-command v2.5.0 requires composer/composer (^1.10.23 || ^2.2.17)
wp-cli/wp-cli-bundle   v2.9.0 requires composer/composer (^1.10.23 || ~2.2.17)
```

This prevents me from installing any package depending on sf/console 6.x (as composer/composer 2.2.x does not allow it. Otoh composer 2.6 does)...

Would it make sense to release the current head version as 2.9.1?

Thanks!

**Comment by danielbachhuber** [comment]
Coming soon! https://github.com/wp-cli/wp-cli/issues/5891
