### ISSUE TITLE
Deployment failing because of `caching_sha2_password` change

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/wp-cli-bundle#666]
In https://github.com/wp-cli/wp-cli-tests/pull/220, we replaced `mysql_native_password` with `caching_sha2_password`.

That seemed to work fine everywhere, but there are warnings & thus failures in the deployment step.

See https://github.com/wp-cli/wp-cli-bundle/actions/runs/11257982684/job/31305127211#step:15:218 and https://github.com/wp-cli/wp-cli-tests/issues/226

**Comment by swissspidy** [comment]
On difference here is that we're using the default provided MySQL server rather than `shogo82148/actions-setup-mysql`	(where we set `default_authentication_plugin=mysql_native_password` too)

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by swissspidy** [comment]
Fixed by #670
