### ISSUE TITLE
Tagged commit for 2.1.0 composer.lock file points to commit before VERSION update

### ISSUE THREAD

**Issue by 0x6d617474** [wp-cli/wp-cli-bundle#68]
Greetings, 

After building a phar for version `2.1.0`, using the tagged version in this repo, I noticed that the version output was `2.1.0-alpha` instead of the expected `2.1.0`.  

It looks like the current `master` branch builds correctly against `2.1.0` and has the correct version in the `--version` output, so re-tagging the `2.1.0` tag should fix it. 

P.S. The link in the issue template for this repo 404's (`http://wp-cli.org/docs/bug-reports/`)

**Comment by schlessera** [comment]
Do you have a specific use case where you need to rebuild the Phar? The one that is officially provided does include the correct version. I'm not sure any non-official build should indeed version itself as the official stable one...?

**Comment by 0x6d617474** [comment]
My main reason for doing so is that I am the maintainer for the `wp-cli` package in the AUR, which has a policy that packages should always be built from source whenever possible, rather than using pre-compiled artifacts.  

I also think it is beneficial for an open source project to have their distributed builds be easily reproducable 1-to-1, to increase transparency and allow for easy auditing.  

I have a workaround in place for the AUR package such that it pulls the correct commit, but it would be nice to have the official tagged version here pointing to the same commits that the distributed phar does.

**Comment by schlessera** [comment]
I retagged the bundle. `v2.1.0` of this package is now locked to `wp-cli/wp-cli@v2.1.0`, instead of `wp-cli/wp-cli@dev-master`.
